# name: Terraform Drift Detection
# on:
# #   schedule:
# #     - cron: '0 18 * * *' # Runs daily at 6pm
#   workflow_dispatch:

# jobs:
#   drift-detection:
#     name: Detect Infrastructure Drift
#     runs-on: ubuntu-latest

#     env:
#       AWS_REGION: ${{ secrets.AWS_REGION }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan -refresh-only #detects drift 
